name: Reusable Docker Build & Push

on:
  workflow_call:
    inputs:
      backend_image_name:
        required: true
        type: string
      frontend_image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_token:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest

    outputs:
      backend_image_url: ${{ steps.meta_backend.outputs.image }}
      frontend_image_url: ${{ steps.meta_frontend.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "Backend: ${{ inputs.backend_image_name }}"
          echo "Frontend: ${{ inputs.frontend_image_name }}"

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      # BACKEND
      - id: meta_backend
        run: echo "image=${{ inputs.backend_image_name }}:${{ inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Build backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ inputs.backend_image_name }}:${{ inputs.tag }}
            ${{ inputs.backend_image_name }}:latest

      # FRONTEND
      - id: meta_frontend
        run: echo "image=${{ inputs.frontend_image_name }}:${{ inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Build frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ inputs.frontend_image_name }}:${{ inputs.tag }}
            ${{ inputs.frontend_image_name }}:latest
